title: ds
email: danschulz44@gmail.com
description: ds
url: "https://danschlz.github.io"

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
